name: separate
on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * *"  # 7:30 AM EST (12:30 UTC)

jobs:
  fetch-emails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install pyzmail36  # For email parsing
      - name: Run email fetcher
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python fetch_emails.py
